baseURL = "https://fablabromagna.org/"
languageCode = "it"
title = "FabLab Romagna"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = "fablabromagna"

[outputs]
  home = ["HTML", "RSS", "JSON"]


############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "Informazioni"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2
  
  [[menu.main]]
  name = "Contatti"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "Informazioni"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2
  
  [[menu.footer]]
  name = "Contatti"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "FabLab Romagna A.P.S."
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
email = "posta@fablabromagna.org"
location = "Cesena, Italy"
# copyright
copyright = "| copyright &copy; 2020 FabLab Romagna A.P.S. |"

  # Preloader
  [params.preloader]
  enable = false
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Iscriviti alla nostra Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################
[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/fablabromagna-org"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/fablabromagna/"

[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/fablabromagna/"

[[params.social]]
title = "more"
icon = "ti-more" # themify icon : https://themify.me/themify-icons
link = "#"

[markup.goldmark.renderer]
unsafe= true
